### PR TITLE
refactor: refactore to improve match to load configuration

### PR DESCRIPTION
**Pull request by danielsoro**

### CODE REVIEW

**Comment by htmfilho** [comment]
Great improvements! Thanks for contributing :)

I'm running to deliver this app. A swim meet is on the way and they need it to compare the results with best times. Docker is not introduced yet. I never thought anyone other than me would be interested on this code :D

**Review by htmfilho — APPROVED** [review]

**Comment by danielsoro** [comment]
> Great improvements! Thanks for contributing :)
> 
> I'm running to deliver this app. A swim meet is on the way and they need it to compare the results with best times. Docker is not introduced yet. I never thought anyone other than me would be interested on this code :D


I started studying and coding in Rust a few days ago and saw your work on my main Github's page... I came here to look a bit about what you are doing and looking at the code I see some stuff where I can help and learn at the same time.

I could add more changes to the code if it is not an issue for you. 
The funny part is that Your project matches exactly with what I'm learning: actix-web, tokio, sqlx and etc.

**Comment by htmfilho** [comment]
You just started and is already writing great code. Congrats! I'm excited about Rust too. Learning with this project. I reached a point of no return. Taking the VM out of the way gives a great feeling.

You're welcome to contribute! Please do. I'm learning with you.

**Comment by danielsoro** [comment]
> Taking the VM out of the way gives a great feeling.

That's my goal, unfortunately, I still need to maintain a bunch of libraries/software with Java/Kotlin daily in the work. The good news is that in the current team, we have a CLI in Go where I can do some code in another language that is not from the JVM ecosystem.

**Comment by htmfilho** [comment]
Me too. Java/Kotlin at work, and Go and Rust at home, helping with my volunteering initiatives.

**Pull request merged**
