### PR TITLE
feat: enabling logging to the server

### PR DESCRIPTION
**Pull request by danielsoro**
With this lib, we can move all MSG to use log::info!/error!/debug!/trace! instead of print!/println!

### CODE REVIEW

**Comment by htmfilho** [comment]
Conflicting with the previous PR.

**Comment by danielsoro** [comment]
> Conflicting with the previous PR.

I'll fix it later during my out-of-work hour!

**Comment by danielsoro** [comment]
@htmfilho it should be as expected, now! :)

**Review by htmfilho — APPROVED** [review]

**Comment by danielsoro** [comment]
Suggestion: you can keep the analysis running when coding. I love this Rust approach, you can get feedback every single time that saves the file:
```shell
cargo watch -x check -x clippy -x run
```

So, if `check` pass, it will execute `Clippy`, if Clippy pass it will execute `run`

**Comment by htmfilho** [comment]
Great! Thanks!

**Pull request merged**
